//
// Created by tschmitz on 11/7/25.
//

#ifndef VERSION_UTIL_HPP
#define VERSION_UTIL_HPP

#include "../logging/include/logging/internal/logging_utils.h"
#include <type_traits>

/**
 * Helper macro for converting Python kwargs to struct fields.
 * @param kwargs_ kwargs parameter from Python.
 * @param key_ The struct field to initialize.
 */
#define KWARG_TO_STRUCT_PARAM(kwargs_, key_)                                   \
    do {                                                                       \
        if ((kwargs_).contains(#key_)) {                                       \
            (key_) = (kwargs_)[#key_].cast<decltype(key_)>();                  \
        }                                                                      \
    } while (false)

template <typename T>
struct NamedValue {
    const char *name;
    const T &value;
    bool check;
};

template <typename T>
struct is_named_value : std::false_type {};

template <typename T>
struct is_named_value<NamedValue<T>> : std::true_type {};

/**
 * @brief Converts a variadic list of named values into a Python dictionary with
 * conditional filtering.
 *
 * This overload applies a predicate to each argument. If the argument has its
 * 'check' flag set and the predicate returns true, the value is replaced with a
 * default value (e.g., py::none()). Otherwise, the original value is stored.
 *
 * @tparam Predicate A callable type used to evaluate the value of each field.
 * @tparam Default The type of the fallback value to be used if the check
 * passes.
 * @tparam Args Variadic pack of NamedValue types generated by NV() or
 * NV_NO_CHECK().
 *
 * @param check A lambda or function object defining the condition (e.g.,
 * [](auto v){ return v == 0; }).
 * @param default_val The value to insert into the dict if the check condition
 * is met (e.g., py::none()).
 * @param args The fields to be processed, wrapped in NamedValue structs.
 *
 * @return py::dict A Python dictionary containing the processed key-value
 * pairs.
 */
template <typename Predicate, typename Default, typename... Args,
          typename =
              std::enable_if_t<!is_named_value<std::decay_t<Predicate>>::value>>
py::dict to_dict(Predicate &&check, Default &&default_val, Args &&...args) {
    static_assert(
        (is_named_value<std::decay_t<Args>>::value && ...),
        "All arguments to to_dict must be wrapped in NV() or NV_NO_CHECK()");

    py::dict dict;

    auto process = [&](auto &&item) {
        if (item.check && check(item.value)) {
            dict[item.name] = default_val;
        } else {
            dict[item.name] = item.value;
        }
    };

    (process(std::forward<Args>(args)), ...);
    return dict;
}

/**
 * @brief Converts a variadic list of named values directly into a Python
 * dictionary.
 *
 * This overload maps each NamedValue directly to a dictionary key-value pair
 * without applying any conditional checks or default values.
 *
 * @tparam Args Variadic pack of NamedValue types generated by NV() or
 * NV_NO_CHECK().
 *
 * @param args The fields to be inserted into the dictionary.
 *
 * @return py::dict A Python dictionary containing the exact keys and values
 * provided.
 */
template <typename... Args>
py::dict to_dict(Args &&...args) {
    py::dict dict;
    ((dict[args.name] = args.value), ...);
    return dict;
}

#define Z_NV(field_, check_)                                                   \
    NamedValue<decltype(field_)> { #field_, field_, check_ }

#define Z_NV_CONTAINER(field_, container_, check_)                             \
    NamedValue<decltype((container_).field_)> {                                \
#field_, (container_).field_, check_                                   \
    }

/**
 * @brief Wraps a field into a NamedValue struct with checking enabled.
 *
 * Automatically detects if the field is a local variable or a member of a
 * container. If a container is provided, it accesses `container.field_`.
 *
 * @param field_ The name of the variable or member to be wrapped.
 * @param container_ (Optional) The instance containing the field.
 *                   If omitted, the field is treated as a local variable.
 */
#define NV(field_, container_...)                                              \
    COND_CODE_0(IS_EMPTY(container_),                                          \
                (Z_NV_CONTAINER(field_, container_, true)),                    \
                (Z_NV(field_, true)))

/**
 * @brief Wraps a field into a NamedValue struct with checking disabled.
 *
 * Maps a field to a Python dictionary key while explicitly bypassing any
 * conditional logic (like "Zero to None" filtering) in the to_dict template.
 *
 * @param field_ The name of the variable or member to be wrapped.
 * @param container_ (Optional) The instance containing the field.
 *                   If omitted, the field is treated as a local variable.
 */
#define NV_NO_CHECK(field_, container_...)                                     \
    COND_CODE_0(IS_EMPTY(container_),                                          \
                (Z_NV_CONTAINER(field_, container_, false)),                   \
                (Z_NV(field_, false)))

#endif // VERSION_UTIL_HPP