if (UNIX AND NOT APPLE)
    set(LINUX_DISTRO "Unknown")
    set(LINUX_VERSION "Unknown")
    set(LINUX_VERSION_MAJOR "Unknown")

    if(EXISTS "/etc/os-release")
        file(STRINGS "/etc/os-release" OS_RELEASE_LINES)

        foreach(line IN LISTS OS_RELEASE_LINES)
            if(line MATCHES "^[ \t]*ID=")
                string(REGEX REPLACE "^[ \t]*ID=\"?([^\"]*)\"?" "\\1" LINUX_DISTRO "${line}")
            elseif(line MATCHES "^[ \t]*VERSION_ID=")
                string(REGEX REPLACE "^[ \t]*VERSION_ID=\"?([^\"]*)\"?" "\\1" LINUX_VERSION "${line}")
            endif()
        endforeach()

        if(LINUX_VERSION MATCHES "^([0-9]+)")
            set(LINUX_VERSION_MAJOR "${CMAKE_MATCH_1}")
        endif()
    endif()

    message("-- Detected Linux distro: ${LINUX_DISTRO}")
    message("-- Detected Linux version: ${LINUX_VERSION}")
    message("-- Detected Linux major version: ${LINUX_VERSION_MAJOR}")
elseif (ERROR_NOT_LINUX)
    message(FATAL_ERROR "Not a Linux distribution")
else ()
    message(STATUS "Not a Linux distribution")
endif()
